In [33]:
# 8.3A
import math
import numpy as np;
f = math.sqrt(5)
x = np.array([[2,-1],[1,2]])/f
x_ = np.linalg.inv(x)
l = np.array([[2,0],[0,-1]])
M = np.dot(np.dot(x,l),x_)
print x
print x_
print np.dot(x,x_)
print M
print M*5
print np.dot(M,np.array([[-1],[2]]))

[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]
[[  1.00000000e+00   0.00000000e+00]
 [  5.55111512e-17   1.00000000e+00]]
[[ 1.4  1.2]
 [ 1.2 -0.4]]
[[ 7.  6.]
 [ 6. -2.]]
[[ 1.]
 [-2.]]


In [36]:
# 8.6
A = np.array([[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]])
B = np.array([[4,0,0,0],[0,3,0,0],[0,0,2,0],[0,0,0,1]])
C = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0]])
print A.dot(B).dot(C)

D1 = np.array([[1,0],[0,0],[0,0],[0,1]])
D2 = np.array([[4,0,0,0,0],[0,3,0,0,0]])
print D1.dot(D2)

[[4 0 0 0 0]
 [0 0 0 1 0]
 [0 0 2 0 0]
 [0 3 0 0 0]]
[[4 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 3 0 0 0]]


In [30]:
#8.7a
import numpy as np
import sklearn
from sklearn.utils.extmath import randomized_svd
from sklearn.decomposition import TruncatedSVD
X = np.array([[1,2,3],[4,5,6]])
print X

svd = TruncatedSVD(n_components=1)
svd.fit(X)
print(svd.singular_values_) 

U, Sigma, VT = randomized_svd(X, 
                              n_components=1,
                              n_iter=5,
                              random_state=None)
print U
print Sigma
print VT
print np.dot(np.dot(U,np.diag(Sigma)),VT)
print np.dot(np.diag(Sigma),VT)
print "============="
a = np.random.randn(1, 1)
print a.shape
P, D, Q = np.linalg.svd(X, full_matrices=False)
print P
print np.diag(D)
print Q
print np.dot(np.diag(D),Q)

[[1 2 3]
 [4 5 6]]
[ 9.508032]
[[ 0.3863177 ]
 [ 0.92236578]]
[ 9.508032]
[[ 0.42866713  0.56630692  0.7039467 ]]
[[ 1.57454629  2.08011388  2.58568148]
 [ 3.75936076  4.96644562  6.17353048]]
[[ 4.07578082  5.38446431  6.69314779]]
(1, 1)
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[[ 9.508032    0.        ]
 [ 0.          0.77286964]]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]]
[[-4.07578082 -5.38446431 -6.69314779]
 [ 0.62290503  0.08685696 -0.44919112]]


In [32]:
#8.7.b
u = np.array([[1],[1]])
v = np.array([[2],[4]])
a = np.array([[2],[2]])
b = np.array([[1],[2]])
print u
print v.T
print np.dot(u,v.T)
print np.dot(a,b.T)

[[1]
 [1]]
[[2 4]]
[[2 4]
 [2 4]]
[[2 4]
 [2 4]]
