In [2]:
# == 
# == 
# == 

import nltk;
import timeit
# nltk.download()

def done():
    print "\n===DONE==="
done() # ============================================================


===DONE===


In [3]:
# == 
# == 
# == 

from nltk.corpus import stopwords
import string
import re

# ==== The Words ====
brown_words = nltk.corpus.brown.words();
print "Corpus Brown Words: ", type(brown_words), len(brown_words), "\n"

# ==== STOP WORDS ====
stop_words = set(stopwords.words('english'))
print "====STOP WORDS====\n",stop_words

# ==== MUST CONTAIN AN ALPHABET CHARACTER ====
regex = "(.*)[a-zA-Z]+(.*)"
regex_pattern = re.compile(regex)
print "\nRegex Pattern Requirement: " + regex
done() # ============================================================

Corpus Brown Words:  <class 'nltk.corpus.reader.util.ConcatenatedCorpusView'> 1161192 

====STOP WORDS====
set([u'all', u'just', u"don't", u'being', u'over', u'both', u'through', u'yourselves', u'its', u'before', u'o', u'don', u'hadn', u'herself', u'll', u'had', u'should', u'to', u'only', u'won', u'under', u'ours', u'has', u"should've", u"haven't", u'do', u'them', u'his', u'very', u"you've", u'they', u'not', u'during', u'now', u'him', u'nor', u"wasn't", u'd', u'did', u'didn', u'this', u'she', u'each', u'further', u"won't", u'where', u"mustn't", u"isn't", u'few', u'because', u"you'd", u'doing', u'some', u'hasn', u"hasn't", u'are', u'our', u'ourselves', u'out', u'what', u'for', u"needn't", u'below', u're', u'does', u"shouldn't", u'above', u'between', u'mustn', u't', u'be', u'we', u'who', u"mightn't", u"doesn't", u'were', u'here', u'shouldn', u'hers', u"aren't", u'by', u'on', u'about', u'couldn', u'of', u"wouldn't", u'against', u's', u'isn', u'or', u'own', u'into', u'yourself', u'down', u

In [4]:
# == 
# == 
# == 

from nltk.corpus import stopwords
import string

debug = False

# Initialize Word Counts
wc = dict()
words = []

#Building Word Counts
j = 0
s = ""
for i in range(len(brown_words)):
    w = brown_words[i].lower()
    if w not in stop_words and regex_pattern.match(w):
        words.append(w)
        wc[w] = wc.get(w, 0) + 1
        
        if debug:
            j+=1
            s = s + " " + w
            if j > 100:
                print s
                s = ""
                j=0

swc = []
for key, value in sorted(wc.iteritems(), key=lambda (k,v): (v,k), reverse=True):
    swc.append([key, value])
                
print "\nBag-Of-Words size", len(swc), ", Top 10: ", swc[:10]
print "\nUnfilteres Words:",len(brown_words),"Filtered:",len(words)

done() # ============================================================


Bag-Of-Words size 47892 , Top 10:  [[u'one', 3292], [u'would', 2714], [u'said', 1961], [u'new', 1635], [u'could', 1601], [u'time', 1598], [u'two', 1412], [u'may', 1402], [u'first', 1361], [u'like', 1292]]

Unfilteres Words: 1161192 Filtered: 530090

===DONE===


In [5]:
# == 
# == Getting Vocab sets
# == 

vocabulary_size = 5000
V = swc[:vocabulary_size]
V_words = []; 
for v in V: 
    V_words.append(v[0])
print "Vocabulary Words ", len(V_words), ", Top 10: ", V_words[:10]
V_index_map = dict()
for i in range(len(V_words)):
    V_index_map[V_words[i]] = i
print "Vocabulary index_map ", len(V_index_map), V_words[0], type(V_words[0])


context_size = 1000
C = swc[:context_size]
C_words = []
for c in C:
    C_words.append(c[0])
print "\nContext Words ", len(C), ", Top 10: ", C[:10]
print "Context Words ", len(C_words), ", Top 10: ", C_words[:10]

C_index_map = dict()
for i in range(len(C_words)):
    C_index_map[C_words[i]] = i
print "Context index_map ", len(C_index_map), C_words[0], type(C_words[0])


window = 2
word_window_words = [None]*(len(words)+window*2)
word_window_words[window:-window] = words
word_window = [None]*(window+window+1)
word_window[(window+1):] = words[:window]
window_range = range(window+window+1)
del window_range[window]
print "\nWord Window", word_window, word_window[window], window_range[:5], window_range[-5:]


done() # ============================================================

Vocabulary Words  5000 , Top 10:  [u'one', u'would', u'said', u'new', u'could', u'time', u'two', u'may', u'first', u'like']
Vocabulary index_map  5000 one <type 'unicode'>

Context Words  1000 , Top 10:  [[u'one', 3292], [u'would', 2714], [u'said', 1961], [u'new', 1635], [u'could', 1601], [u'time', 1598], [u'two', 1412], [u'may', 1402], [u'first', 1361], [u'like', 1292]]
Context Words  1000 , Top 10:  [u'one', u'would', u'said', u'new', u'could', u'time', u'two', u'may', u'first', u'like']
Context index_map  1000 one <type 'unicode'>

Word Window [None, None, None, u'fulton', u'county'] None [0, 1, 3, 4] [0, 1, 3, 4]

===DONE===


In [5]:
# Test bed
temp = u'one'
print "<TEST>", temp, type(temp), regex_pattern.match(temp)
temp = u'.'
print "<TEST>", temp, type(temp), regex_pattern.match(temp)



done() # ============================================================

<TEST> one <type 'unicode'> <_sre.SRE_Match object at 0x10f7cdcf0>
<TEST> . <type 'unicode'> None

===DONE===


In [69]:
# == 
# == 
# == 
DEBUG = False


from ipywidgets import FloatProgress
from IPython.display import display
import timeit


print "C:", type(C),type(C[0]),C[:5]
word_context = {"word":[]}
print "Word Context:",len(word_context)

words_length = len(words)
f = FloatProgress(min=0, max=100)
display(f)
ff = FloatProgress(min=0, max=100)
display(ff)

start = timeit.default_timer()
print "Start:",start
# for index in range(2000):
for index in range(words_length):
    f.value = index / float(words_length)*100
    ff.value = (index-words_length+1000.)/1000.*100.
    word = words[index]
    if word not in V_words:
        continue;
    word_window = word_window_words[index:index+window+window+1];
    word_context[word] = [0]*len(C_words)
    for i in window_range:
        if word_window[i] in C_words:
            cw = word_window[i]
            word_context[word][C_index_map[cw]] += 1
            if DEBUG and sum(word_context[word]) > 1:
                print word,cw,word_context[word][C_index_map[cw]],sum(word_context[word])
#             if word == cw:
#                 print word_window
stop = timeit.default_timer()
print "Stop:",stop
print "Time:",stop - start 

done() # ============================================================

C: <type 'list'> <type 'list'> [[u'one', 3292], [u'would', 2714], [u'said', 1961], [u'new', 1635], [u'could', 1601]]
Word Context: 1


FloatProgress(value=0.0)

FloatProgress(value=0.0)

Start: 1521040072.91
Stop: 1521040663.35
Time: 590.436729908

===DONE===


In [6]:
import numpy as np
import json


# print len(word_context), word_context.keys()[:5],[sum(li) for li in word_context.values()[:5]]
# sorted_word_context = []
# for key, value in sorted(word_context.iteritems(), key=lambda (k,v): (sum(v),k), reverse=True):
#     sorted_word_context.append([key, sum(value),value])
# 
# print len(sorted_word_context),[row[:2] for row in sorted_word_context[:5]]
# 
# with open("sorted_word_context.txt", 'wb') as dump:
#     dump.write(json.dumps(sorted_word_context))
with open("sorted_word_context.txt", 'rb') as dump:
    lines = json.loads(dump.read())
sorted_word_context = lines

# with open("sorted_word_context.txt", 'w') as out_file:
#     out_file.write(str(sorted_word_context))

# with open('sorted_word_context.txt') as f:
#     lines = f.read()
print type(lines),len(lines),[row[:2] for row in lines[:5]]
    

done() # ============================================================

<type 'list'> 5000 [[u'zero', 4], [u'youngsters', 4], [u'works', 4], [u"women's", 4], [u'women', 4]]

===DONE===


In [17]:
n = float(sum([wc[c] for c in C_words]))
print n
prob_c = [wc[c]/n for c in C_words]
print prob_c[:5], type(prob_c)

rows_height, columns_width = 20, 10
rows_height, columns_width = len(V_words),len(C_words)
print rows_height, columns_width 
X = np.zeros((rows_height,columns_width))
PX = np.zeros((rows_height,columns_width))
for x in range(rows_height):
    X[x,:] = sorted_word_context[x][2][:columns_width]
print "X", X
# print "\n\nWWWWWWWWWWWWWWWWWWWWWWW\n\n"
# print PX

done() # ============================================================

234748.0
[0.014023548656431578, 0.011561333855879496, 0.00835363879564469, 0.006964915569035732, 0.006820079404297374] <type 'list'>
5000 1000
X [[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]

===DONE===


In [62]:
import numpy as np
wc_matrix = np.array([[0.,1.,2.,2.,3.,4.],[4.,4.,3.,4.,2.,1.],[0.,0.,5.,5.,0.,0.]])
wc_matrix = np.transpose(wc_matrix)
print wc_matrix
sum_wc_rows = [sum(wc_matrix[i,:]) for i in range(wc_matrix.shape[0])]
sum_wc = sum(sum_wc_rows)
prob_c = [float(row_sum)/sum_wc for row_sum in sum_wc_rows]
prob_c_matrix = np.transpose(np.tile(prob_c,(wc_matrix.shape[1],1)))
log_prob_c_matrix = np.log(prob_c_matrix)
print "\n\nSum of WC rows",sum_wc_rows,"\nTotal Sum", sum_wc
print "Context word probabilities", prob_c,"\nlog of prob_c",np.log(prob_c),prob_c_matrix,"\n",log_prob_c_matrix,"\n\n"

wc_prob_matrix = np.zeros(wc_matrix.shape)
for i in range(wc_matrix.shape[0]):
    wc_prob_matrix[i,:] = (wc_matrix[i,:]/sum_wc_rows[i])
print "A", wc_prob_matrix
log_wc_prob_matrix = np.log(wc_prob_matrix)
print "A1",log_wc_prob_matrix
log_wc_prob_matrix[log_wc_prob_matrix==-np.inf]=0
print "A2",log_wc_prob_matrix
print "B", log_prob_c_matrix
phi_matrix = np.maximum(np.zeros(log_wc_prob_matrix.shape),log_wc_prob_matrix/log_prob_c_matrix)
print "C", phi_matrix

[[ 0.  4.  0.]
 [ 1.  4.  0.]
 [ 2.  3.  5.]
 [ 2.  4.  5.]
 [ 3.  2.  0.]
 [ 4.  1.  0.]]


Sum of WC rows [4.0, 5.0, 10.0, 11.0, 5.0, 5.0] 
Total Sum 40.0
Context word probabilities [0.10000000000000001, 0.125, 0.25, 0.27500000000000002, 0.125, 0.125] 
log of prob_c [-2.30258509 -2.07944154 -1.38629436 -1.29098418 -2.07944154 -2.07944154] [[ 0.1    0.1    0.1  ]
 [ 0.125  0.125  0.125]
 [ 0.25   0.25   0.25 ]
 [ 0.275  0.275  0.275]
 [ 0.125  0.125  0.125]
 [ 0.125  0.125  0.125]] 
[[-2.30258509 -2.30258509 -2.30258509]
 [-2.07944154 -2.07944154 -2.07944154]
 [-1.38629436 -1.38629436 -1.38629436]
 [-1.29098418 -1.29098418 -1.29098418]
 [-2.07944154 -2.07944154 -2.07944154]
 [-2.07944154 -2.07944154 -2.07944154]] 


A [[ 0.          1.          0.        ]
 [ 0.2         0.8         0.        ]
 [ 0.2         0.3         0.5       ]
 [ 0.18181818  0.36363636  0.45454545]
 [ 0.6         0.4         0.        ]
 [ 0.8         0.2         0.        ]]
A1 [[       -inf  0.                

/Users/bmehaffy/anaconda/envs/tensorflow2.7/lib/python2.7/site-packages/ipykernel_launcher.py:17: RuntimeWarning: divide by zero encountered in log


In [63]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(phi_matrix)
print pca.components

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)